/* TradePanel multi-strategy public-demo layer. All outputs are deterministic simulations. */
const MODE_DEFS={
 day:{label:'Day Trading',timeframe:'1m · 2m · 5m · 15m',cycle:'90 seconds',data:'Intraday OHLC, volume, VWAP, EMA, RSI, ATR, SQZMOM'},
 swing:{label:'Swing Trading',timeframe:'4H · 1D · 1W',cycle:'On demand',data:'Daily OHLC, volume, EMA/SMA, RSI, ATR, relative strength'},
 long:{label:'Long-Term',timeframe:'1D · 1W · 1M',cycle:'On demand',data:'Long-horizon price history + simulated fundamentals'}
};
const RAW_STRATEGIES={
 day:[
  ['tp-v1','TradePanel Strategy v1.0','Momentum / pullback','Minutes to hours','Trending, liquid sessions','v1'],
  ['opening-range','Opening Range Breakout','Breakout','Minutes to hours','High-volume directional opens','breakout'],
  ['vwap-pullback','VWAP Pullback Continuation','Trend continuation','Minutes to hours','Orderly intraday trends','vwap'],
  ['momentum-rvol','Relative-Volume Momentum','Momentum','Minutes to hours','Catalyst and volume expansion','momentum'],
  ['ema-trend','EMA 9/21 Trend Continuation','Trend','Minutes to hours','Persistent directional tape','ema'],
  ['squeeze-release','Volatility Squeeze Release','Volatility breakout','Minutes to hours','Compression before expansion','squeeze'],
  ['breakout-retest','Breakout and Retest','Price action','Minutes to hours','Clean levels with confirmation','retest'],
  ['mean-revert-vwap','VWAP Mean Reversion','Mean reversion','Minutes','Range-bound, liquid sessions','mean'],
  ['rsi-reversal','RSI Exhaustion Reversal','Reversal','Minutes to hours','Extended moves losing momentum','reversal'],
  ['volume-breakout','Volume-Confirmed High Break','Breakout','Minutes to hours','Range highs with participation','volume']
 ],
 swing:[
  ['daily-breakout','Daily Breakout','Breakout','2–15 trading days','Consolidation resolving with volume','breakout'],
  ['ema-pullback','20/50 EMA Pullback','Trend continuation','3–20 trading days','Established daily trends','ema'],
  ['bull-flag','Bull Flag Continuation','Chart pattern','2–15 trading days','Strong impulse then tight pullback','flag'],
  ['rsi-trend','RSI Trend Regime','Momentum','3–20 trading days','RSI holding a bullish regime','rsi'],
  ['sma-cross','50/200 SMA Trend Cross','Trend','Weeks to months','Major trend transitions','cross'],
  ['atr-breakout','ATR Expansion Breakout','Volatility','2–15 trading days','Volatility expansion from a base','atr'],
  ['relative-strength','Market Relative Strength','Relative strength','1–8 weeks','Leaders outperforming benchmark','rs'],
  ['multi-timeframe','Weekly/Daily Alignment','Multi-timeframe','1–8 weeks','Weekly and daily trends aligned','mtf'],
  ['support-bounce','Support Reclaim','Price action','2–15 trading days','Pullback into established support','support'],
  ['channel-break','Trend Channel Break','Breakout','3–30 trading days','Orderly channel resolves','channel']
 ],
 long:[
  ['quality-value','Quality at a Reasonable Price','Quality / value','1–5 years','Durable profitable businesses at disciplined valuations','quality'],
  ['deep-value','Fundamental Value','Value','1–5 years','Discounted valuations with viable fundamentals','value'],
  ['growth-quality','Profitable Growth','Growth / quality','1–5 years','Sustained revenue and earnings growth','growth'],
  ['dividend-growth','Dividend Growth','Income / quality','3–10 years','Stable cash generation and distributions','dividend'],
  ['wide-moat','Durable Quality Compounders','Quality','3–10 years','High returns on capital and balance-sheet strength','compounder'],
  ['fcf-yield','Free-Cash-Flow Yield','Value / cash flow','1–5 years','Strong cash generation relative to price','fcf'],
  ['low-debt','Balance-Sheet Strength','Quality / risk','1–5 years','Low leverage and resilient profitability','debt'],
  ['earnings-revision','Earnings Growth & Revision','Growth / momentum','6–24 months','Improving earnings trajectory','earnings'],
  ['trend-200d','200-Day Trend Filter','Long-term momentum','6–24 months','Persistent long-horizon uptrends','trend'],
  ['factor-blend','Quality–Value–Momentum Blend','Multi-factor','1–5 years','Diversified factor leadership','blend']
 ]
};
function normalizedStrategy(mode,row,index){
 const[id,name,category,holding,conditions,profile]=row;
 return {strategy_id:id,name,mode,category,description:`${name} scans for ${category.toLowerCase()} evidence suited to ${conditions.toLowerCase()}.`,holding_period:holding,
  market_conditions:conditions,required_data:MODE_DEFS[mode].data.split(', '),hard_filters:strategyRules(profile,mode),soft_filters:softRules(profile,mode),
  entry_rules:['Wait for the strategy trigger to confirm','Enter only at the displayed deterministic demo level'],exit_rules:['Exit on invalidation or target','Reassess if the setup regime changes'],
  stop_method:mode==='long'?'Thesis or long-term trend invalidation':profile==='atr'?'ATR-based invalidation':'Structure / ATR invalidation',
  target_method:mode==='long'?'Valuation, thesis and trailing review':'Minimum risk multiple / structure target',minimum_rr:mode==='long'?1.5:2,
  confidence_method:'Weighted pass rate across strategy-specific hard and supporting rules',scanner_compatible:true,
  data_status:mode==='long'?'SIMULATED FUNDAMENTALS + SIMULATED PRICE DATA':'SIMULATED MARKET DATA',status:index===0?'DEFAULT':'AVAILABLE',profile};
}
function strategyRules(p,m){
 if(m==='long') return ({quality:['ROIC ≥ 12%','Positive free cash flow','Debt / equity controlled','Valuation ceiling'],value:['Forward P/E ≤ 24','FCF yield ≥ 3%','Positive earnings','Debt / equity controlled'],growth:['Revenue growth ≥ 8%','EPS growth ≥ 10%','Positive free cash flow','ROIC ≥ 10%'],dividend:['Dividend yield ≥ 1.5%','Positive FCF','Debt / equity controlled','Revenue stability'],compounder:['ROIC ≥ 15%','ROE ≥ 15%','Positive FCF','200-day trend intact'],fcf:['FCF yield ≥ 4%','Positive earnings','Debt / equity controlled','Revenue not contracting'],debt:['Debt / equity ≤ 0.8','Positive FCF','ROIC ≥ 10%','Profitability positive'],earnings:['EPS growth ≥ 12%','Revenue growth ≥ 6%','Positive revisions proxy','200-day trend intact'],trend:['Price above SMA 200','Positive 12-month relative strength','Profitable business','Debt screen'],blend:['Quality rank passes','Value rank passes','Momentum rank passes','Positive FCF']})[p];
 return ({v1:['Market bias aligned','Trend structure aligned','Price aligned with VWAP / EMA 21','SQZMOM transition confirmed','Valid trigger candle','Risk / reward ≥ 2.0'],breakout:['Breakout level cleared','Relative volume expansion','Trend aligned','Risk / reward ≥ 2.0'],vwap:['Price holds VWAP','EMA trend aligned','Pullback proximity valid','Risk / reward ≥ 2.0'],momentum:['Relative volume ≥ 1.5×','Momentum positive','RSI supports continuation','Risk / reward ≥ 2.0'],ema:['EMA 9 / 21 alignment','Price follows trend','Structure confirms','Risk / reward ≥ 2.0'],squeeze:['SQZMOM release','ATR expansion','Direction aligned','Risk / reward ≥ 2.0'],retest:['Level reclaimed','Retest holds','Volume confirms','Risk / reward ≥ 2.0'],mean:['Distance from VWAP extended','RSI stretched','Range regime','Risk / reward ≥ 1.8'],reversal:['RSI exhaustion','Reversal candle','Momentum decelerating','Risk / reward ≥ 2.0'],volume:['Range high cleared','Relative volume ≥ 1.8×','Close confirms','Risk / reward ≥ 2.0'],flag:['Daily trend positive','Controlled pullback','Volume contraction then expansion','Risk / reward ≥ 2.0'],rsi:['RSI bullish regime','Daily trend positive','Structure confirms','Risk / reward ≥ 2.0'],cross:['SMA 50 above SMA 200','Price above SMA 50','Momentum positive','Risk / reward ≥ 2.0'],atr:['ATR expansion','Daily breakout','Volume confirms','Risk / reward ≥ 2.0'],rs:['Relative strength ≥ 70','Daily trend positive','Volume healthy','Risk / reward ≥ 2.0'],mtf:['Weekly trend positive','Daily trend positive','Momentum aligned','Risk / reward ≥ 2.0'],support:['Support reclaim','Bullish daily candle','ATR risk defined','Risk / reward ≥ 2.0'],channel:['Channel boundary cleared','Volume confirms','Daily momentum positive','Risk / reward ≥ 2.0']})[p]||['Trend aligned','Volume confirms','Risk defined'];
}
function softRules(p,m){return m==='long'?['Valuation versus peers','Five-year profitability stability','Relative strength','Earnings consistency','Margin quality']:['Volume confirmation','Momentum strength','Multi-timeframe alignment','Clean market structure','Favorable ATR','Trigger quality','Market regime fit'];}
const STRATEGY_CATALOG=Object.fromEntries(Object.entries(RAW_STRATEGIES).map(([m,rows])=>[m,rows.map((r,i)=>normalizedStrategy(m,r,i))]));
let selectedMode='day',selectedStrategyId='tp-v1',customEnabled=false,customRules=[];
const profileMetric={v1:'structure',breakout:'breakout',vwap:'vwap',momentum:'relVol',ema:'trend',squeeze:'squeeze',retest:'retest',mean:'mean',reversal:'reversal',volume:'relVol',flag:'pullback',rsi:'rsi',cross:'smaCross',atr:'atrExpand',rs:'relativeStrength',mtf:'mtf',support:'support',channel:'channel',quality:'roic',value:'pe',growth:'revGrowth',dividend:'dividend',compounder:'roe',fcf:'fcfYield',debt:'debtEquity',earnings:'epsGrowth',trend:'above200',blend:'factorScore'};
function currentStrategy(){return STRATEGY_CATALOG[selectedMode].find(s=>s.strategy_id===selectedStrategyId)||STRATEGY_CATALOG[selectedMode][0]}
function enrich(u,s,seed){
 const o=build(u,seed),r=mkRnd(hash(`${u.tk}|${s.strategy_id}|${seed}`));
 Object.assign(o,{strategy_id:s.strategy_id,strategy_name:s.name,mode:s.mode,breakout:r()>.38,vwap:r()>.32,trend:r()>.28,retest:r()>.42,mean:r()>.48,reversal:r()>.55,pullback:r()>.32,smaCross:r()>.4,atrExpand:r()>.42,relativeStrength:Math.round(35+r()*65),mtf:r()>.34,support:r()>.4,channel:r()>.46,
  pe:+(8+r()*35).toFixed(1),revGrowth:+(-2+r()*28).toFixed(1),epsGrowth:+(-5+r()*35).toFixed(1),fcfYield:+(r()*9).toFixed(1),roe:+(5+r()*28).toFixed(1),roic:+(4+r()*25).toFixed(1),debtEquity:+(r()*1.8).toFixed(2),dividend:+(r()*4).toFixed(1),above200:r()>.25,factorScore:Math.round(35+r()*65)});
 return evaluateStrategy(o,s);
}
function profilePass(o,p){return ({v1:o.structure!=='Sideways'&&o.transOK&&o.rr>=2,breakout:o.breakout&&o.relVol>=1.1,vwap:o.vwap&&o.trend,momentum:o.relVol>=1.5&&o.rsi>=48,ema:o.trend&&o.structure!=='Sideways',squeeze:o.squeeze==='squeeze_off'&&o.atr>=1,retest:o.retest&&o.breakout,mean:o.mean&&((o.rsi<45)||(o.rsi>65)),reversal:o.reversal&&((o.rsi<40)||(o.rsi>70)),volume:o.breakout&&o.relVol>=1.8,flag:o.pullback&&o.trend,rsi:o.rsi>=50&&o.rsi<=75,cross:o.smaCross&&o.trend,atr:o.atrExpand&&o.atr>=1.1,rs:o.relativeStrength>=70&&o.trend,mtf:o.mtf&&o.trend,support:o.support&&o.rsi>=42,channel:o.channel&&o.relVol>=1.1,quality:o.roic>=12&&o.fcfYield>1&&o.debtEquity<=1.2,value:o.pe<=24&&o.fcfYield>=3,growth:o.revGrowth>=8&&o.epsGrowth>=10,dividend:o.dividend>=1.5&&o.fcfYield>1,compounder:o.roic>=15&&o.roe>=15,fcf:o.fcfYield>=4&&o.epsGrowth>0,debt:o.debtEquity<=.8&&o.roic>=10,earnings:o.epsGrowth>=12&&o.revGrowth>=6,trend:o.above200&&o.relativeStrength>=55,blend:o.factorScore>=65&&o.roic>=10})[p];}
function evaluateStrategy(o,s){
 const primary=profilePass(o,s.profile),rrOK=o.rr>=s.minimum_rr;
 const checks=s.hard_filters.map((t,i)=>({t,ok:i===0?primary:i===s.hard_filters.length-1&&/Risk/.test(t)?rrOK:((hash(o.tk+t+s.strategy_id+SCAN_N)%100)>=30),why:`${t} not confirmed in this deterministic scan`}));
 if(customEnabled&&customRules.length){const values=customRules.map(r=>testCustom(o,r));let customPass=values[0];for(let i=1;i<values.length;i++)customPass=customRules[i].logic==='OR'?(customPass||values[i]):(customPass&&values[i]);checks.push({t:`Custom rule: ${customRules.map((r,i)=>`${i?r.logic+' ':''}${r.field} ${r.op} ${r.value}`).join(' ')}`,ok:customPass,why:'Custom condition expression not met'});}
 const fails=checks.filter(x=>!x.ok),soft=s.soft_filters.map(t=>({t,ok:(hash(o.tk+t+s.strategy_id+SCAN_N)%100)>=35})),softPass=soft.filter(x=>x.ok).length;
 Object.assign(o,{hard:checks,soft,fails,softPass,valid:!fails.length,conf:!fails.length?Math.round(68+(softPass/soft.length)*32):0,decision:!fails.length?(selectedMode==='long'?'RESEARCH CANDIDATE':'VALID SETUP'):'NO TRADE'});return o;
}
function testCustom(o,r){const map={Price:o.px,Volume:parseFloat(o.vol),RelativeVolume:o.relVol,RSI:o.rsi,ATR:o.atr,MinimumRR:o.rr,RevenueGrowth:o.revGrowth,EPSGrowth:o.epsGrowth,FCFYield:o.fcfYield,ROIC:o.roic,DebtEquity:o.debtEquity,RelativeStrength:o.relativeStrength};const v=Number(map[r.field]??0),x=Number(r.value);return r.op==='>'?v>x:r.op==='<'?v<x:r.op==='>='?v>=x:v<=x;}
runFullScan=function(){const s=currentStrategy();RESULTS=UNIV.map(u=>enrich(u,s,SCAN_N));SCANNED=true};
function modeChanged(v){selectedMode=v;selectedStrategyId=STRATEGY_CATALOG[v][0].strategy_id;customEnabled=false;customRules=[];runFullScan();RENDER.scan();buildNav()}
function strategyChanged(v){selectedStrategyId=v;customEnabled=false;customRules=[];runFullScan();RENDER.scan();buildNav()}
function toggleCustom(){customEnabled=!customEnabled;if(customEnabled&&!customRules.length)customRules=[{logic:'IF',field:selectedMode==='long'?'ROIC':'RelativeVolume',op:'>=',value:selectedMode==='long'?12:1.5}];RENDER.scan()}
function addRule(){if(customRules.length>=3)return toast('Custom demo supports up to three conditions','dn');customRules.push({logic:customRules.length?'AND':'IF',field:selectedMode==='long'?'RevenueGrowth':'RSI',op:'>=',value:selectedMode==='long'?8:50});RENDER.scan()}
function removeRule(i){customRules.splice(i,1);RENDER.scan()}
function updateRule(i,k,v){customRules[i][k]=v}
function customFields(){return selectedMode==='long'?['Price','RevenueGrowth','EPSGrowth','FCFYield','ROIC','DebtEquity','RelativeStrength']:selectedMode==='swing'?['Price','Volume','RelativeVolume','RSI','ATR','MinimumRR','RelativeStrength']:['Price','Volume','RelativeVolume','RSI','ATR','MinimumRR']}
function renderRules(){return `<div class="custom-panel"><div class="card-t">Custom Strategy — ${MODE_DEFS[selectedMode].label}</div><div class="card-x">Build up to three simple deterministic demo conditions. Values are evaluated against the simulated scan dataset.</div>${customRules.map((r,i)=>`<div class="rule-row"><div class="rule-logic">${i?`<select class="sel" onchange="updateRule(${i},'logic',this.value)"><option ${r.logic==='AND'?'selected':''}>AND</option><option ${r.logic==='OR'?'selected':''}>OR</option></select>`:'IF'}</div><select class="sel" onchange="updateRule(${i},'field',this.value)">${customFields().map(f=>`<option ${f===r.field?'selected':''}>${f}</option>`).join('')}</select><select class="sel" onchange="updateRule(${i},'op',this.value)">${['>=','>','<=','<'].map(x=>`<option ${x===r.op?'selected':''}>${x}</option>`).join('')}</select><input class="inp rule-value mono" type="number" value="${r.value}" onchange="updateRule(${i},'value',this.value)"><button class="btn" onclick="removeRule(${i})">×</button></div>`).join('')}<button class="btn sm" style="margin-top:10px" onclick="addRule()">+ Add condition</button></div>`}
RENDER.scan=()=>{const s=currentStrategy(),valid=RESULTS.filter(o=>o.valid);$('pgS').textContent=`${MODE_DEFS[selectedMode].label} · ${s.name} · simulated deterministic results`;
 $('view').innerHTML=`<div class="demo-banner"><b>PUBLIC PORTFOLIO DEMO — SIMULATED DEMO DATA.</b> No live market or fundamental-data feed is connected. No brokerage connection or order execution is available. Strategies are educational scanner concepts, not promises of performance.</div>
 <div class="card anim" style="margin-bottom:13px"><div class="card-h"><div><div class="card-t">Open Scanner</div><div class="card-x">Choose a trading mode and a genuinely differentiated strategy profile</div></div><span class="mode-chip">${MODE_DEFS[selectedMode].label.toUpperCase()}</span></div>
 <div class="scan-config"><div class="fld"><label>TRADING MODE</label><select class="sel" onchange="modeChanged(this.value)">${Object.entries(MODE_DEFS).map(([k,v])=>`<option value="${k}" ${k===selectedMode?'selected':''}>${v.label}</option>`).join('')}</select></div><div class="fld"><label>STRATEGY</label><select class="sel" onchange="strategyChanged(this.value)">${STRATEGY_CATALOG[selectedMode].map(x=>`<option value="${x.strategy_id}" ${x.strategy_id===s.strategy_id?'selected':''}>${x.name}</option>`).join('')}</select></div><button class="btn ${customEnabled?'act':''}" onclick="toggleCustom()">${customEnabled?'✓ ':''}Custom Strategy</button></div>
 <div class="strategy-hero"><div style="display:flex;align-items:center;gap:9px;flex-wrap:wrap"><b>${s.name}</b><span class="tag t-bl">${s.category}</span><span class="tag t-mut">${s.status}</span></div><div class="strategy-desc">${s.description}</div><div class="strategy-meta"><span class="tag t-mut">Hold: ${s.holding_period}</span><span class="tag t-mut">${MODE_DEFS[selectedMode].timeframe}</span><span class="tag t-am">${s.data_status}</span></div></div>${customEnabled?renderRules():''}
 <button class="btn pri" style="width:100%;margin-top:14px" id="rescanBtn" onclick="rescan()">◈ START SCAN</button></div>
 <div class="grid g21 anim" style="margin-bottom:13px"><div class="card"><div class="card-h"><div><div class="card-t">Strategy Logic</div><div class="card-x">Normalized catalog fields drive this panel and the evaluator</div></div><span class="tag t-up">SCANNER COMPATIBLE</span></div><div class="grid g2"><div><div class="card-x" style="margin-bottom:7px">HARD FILTERS — ALL MUST PASS</div><div class="filter-list">${s.hard_filters.map((f,i)=>`<div class="frow"><span class="fnum hard">${i+1}</span>${f}</div>`).join('')}</div></div><div><div class="card-x" style="margin-bottom:7px">SUPPORTING CONFIDENCE SIGNALS</div><div class="filter-list">${s.soft_filters.map((f,i)=>`<div class="frow"><span class="fnum">${i+1}</span>${f}</div>`).join('')}</div><div class="data-note">Required: ${s.required_data.join(', ')}</div></div></div></div>
 <div class="card"><div class="card-h"><div><div class="card-t">Scan Context</div><div class="card-x">Mode-specific cadence and data assumptions</div></div></div><div class="cond"><span>Mode</span><b>${MODE_DEFS[selectedMode].label}</b></div><div class="cond"><span>Holding period</span><b>${s.holding_period}</b></div><div class="cond"><span>Timeframes</span><b class="mono">${MODE_DEFS[selectedMode].timeframe}</b></div><div class="cond"><span>Cadence</span><b>${MODE_DEFS[selectedMode].cycle}</b></div><div class="cond"><span>Universe</span><b class="mono">${UNIV.length} simulated symbols</b></div><div class="cond"><span>Valid candidates</span><b class="pos">${valid.length}</b></div></div></div><div id="out"></div>`;drawResults();};
rescan=function(){if(SCANNING)return;SCANNING=true;SCAN_N++;const b=$('rescanBtn');b.disabled=true;b.innerHTML='<span class="spinner"></span> Scanning simulated data…';$('out').innerHTML=`<div class="card"><div class="scan-prog-h"><span id="sTxt">Loading deterministic ${MODE_DEFS[selectedMode].label.toLowerCase()} dataset…</span><span id="sPct">0%</span></div><div class="prog"><div class="prog-f" id="sFill" style="background:var(--up)"></div></div></div>`;let p=0;const iv=setInterval(()=>{p+=20;const f=$('sFill');if(f){f.style.width=p+'%';$('sPct').textContent=p+'%'}if(p>=100){clearInterval(iv);SCANNING=false;runFullScan();buildNav();RENDER.scan();toast(`Scan complete — ${RESULTS.filter(o=>o.valid).length} candidates via ${currentStrategy().name}`,'ok')}},180)};
const baseCard=card;card=function(o,i){let html=baseCard(o,i).replace(/TradePanel Strategy v1\.0/g,o.strategy_name||currentStrategy().name);if(selectedMode==='long'){const fg=`<div class="fund-grid"><div class="fund"><span>FORWARD P/E</span><b>${o.pe}×</b></div><div class="fund"><span>REV GROWTH</span><b>${o.revGrowth}%</b></div><div class="fund"><span>ROIC</span><b>${o.roic}%</b></div><div class="fund"><span>FCF YIELD</span><b>${o.fcfYield}%</b></div></div>`;html=html.replace('<div class="opp-sqz">',fg+'<div class="opp-sqz">')}return html};
const baseOpenStock=openStock;openStock=function(tk){baseOpenStock(tk);const co=document.querySelector('.m-co');if(co)co.textContent=`${RESULTS.find(x=>x.tk===tk).name} · ${MODE_DEFS[selectedMode].label} review · ${currentStrategy().name} · SIMULATED DATA`;};
runFullScan();buildNav();RENDER.scan();
